version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./custom_nodes:/home/node/.n8n/custom
    restart: unless-stopped
    networks:
      - ecommerce_network

  postgres:
    image: postgres:13
    container_name: postgres_ecommerce
    environment:
      - POSTGRES_DB=ecommerce_research
      - POSTGRES_USER=researcher
      - POSTGRES_PASSWORD=research123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - ecommerce_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ecommerce_network

volumes:
  n8n_data:
  postgres_data:
  redis_data:

networks:
  ecommerce_network:
    driver: bridge